#!/usr/bin/env bash

set -e

declare -a trees
trees=("$@")

pack_file() {
  # 文件路径
  local file=$1
  # 从tree文件夹开始的相对路径
  local file_relative=$2
  local dir_relative
  dir_relative=$(dirname "$file_relative")
  # mkdir
  echo "# Generate file: $file_relative"
  echo 'mkdir -p "'"$dir_relative"'"'
  echo 'cat >'"$file_relative"' <<"EOF"'
  cat "$file"
  echo 'EOF'
  echo '#================================='
  echo
}

for tree in "${trees[@]}"; do
  full_tree_path=`(cd "${tree}" && pwd)`
  tree_name=$(basename "$tree")
  files=($(find -E "${full_tree_path%%/}" \
    -iregex '.+\.h|.+\.m|.+\.mm|.+\.c|.+\.cc|.+\.cpp|.+\.hpp' -type f))
  for file in "${files[@]}"; do
    relative_file_path=${file#$full_tree_path}
    relative_file_path="${tree_name}$relative_file_path"
    pack_file "$file" "$relative_file_path"
  done
done
