#!/usr/bin/env bash

{
  while read -r ff ; do
    func_name=$(basename "$ff" '.sh' | tr ' -' '__')
    if [ -x "$ff" ] && ! type "$func_name" >/dev/null 2>&1 ; then
      eval "$func_name"'() { bash "'"${ff}"'" ; }'
    elif expr "$ff" : '.*func.sh$' > /dev/null ; then
      . "$ff"
    fi
  done
} < <(find "$@" -type f)
