#!/usr/bin/env bash
set -eu

# 第几列
col_index=0
while [ "$#" -gt 0 ] ; do
  key="$1"
  case $key in
      -c|--col-index)
      col_index="$2"
      shift ; shift
      ;;
  esac
done

ret=0

while read -r -a nums ; do
  num="${nums[$col_index]}"
  if ! [[ "$num" =~ (^|-)[0-9]+ ]] ; then
    continue
  fi
  ret=$(printf '%f + %f\n' "$ret" "$num" | bc)
done

echo "$ret"
