#!/usr/bin/env bash
set -e
if [ $# -ge 1 ] ; then
  declare -a args
  args=("$@")
else
  read -r -a args
fi

declare -a grand_ret=()
for str in "${args[@]}" ; do
  IFS='-_' read -r -a words <<<"$str"
  ret=''
  for wd in "${words[@]}" ; do
    ret="${ret}${wd^?}"
  done
  grand_ret+=("$ret")
done

echo "${grand_ret[*]}"
