#!/usr/bin/env bash
set -eu
if ! shopt -s nullglob globstar ; then
  os_name="$(uname | tr '[:upper:]' '[:lower:]')"
  if [ "$os_name" = "darwin" ] ; then
    brew install bash
  elif [ "$os_name" = "linux" ] ; then
    sudo apt install bash
  else
    printf 'Very ancient version of bash detected. Go update it.\n'
  fi
  exit 1
fi

declare -a suffix=()
if [ $# -gt 0 ] ; then
  suffix+=("$@")
else
  suffix+=('log')
fi

list=
for suf in "${suffix[@]}" ; do
  if [ -z "$list" ] ; then
    list="$suf"
  else
    list="${list},$suf"
  fi
done

if [ "${#suffix[@]}" -gt 1 ] ; then
  eval "cat ./**/*.{$list}"
else
  eval "cat ./**/*.$list"
fi
