#!/usr/bin/env bash
set -eu
filename_glob=${1:-*.log}

declare -a file_list=()
file_list_raw="$(find . -name "$filename_glob")"
{
  while read -r line ; do
    file_list+=("$line")
  done
} <<<"$file_list_raw"

for ff in "${file_list[@]}" ; do
  printf '/// file: %s\n\n' "$ff"
  cat "$ff"
done
