#!/usr/bin/env bash
set -eu
if ! shopt -s nullglob globstar ; then
  os_name="$(uname | tr '[:upper:]' '[:lower:]')"
  if [ "$os_name" = "darwin" ] ; then
    brew install bash
  elif [ "$os_name" = "linux" ] ; then
    sudo apt install bash
  else
    printf 'Very ancient version of bash detected. Go update it.\n'
  fi
  exit 1
fi

declare -a suffix=()
if [ $# -gt 0 ] ; then
  suffix+=("$@")
else
  suffix+=('log')
fi

suf_list=
for suf in "${suffix[@]}" ; do
  if [ -z "$suf_list" ] ; then
    suf_list="$suf"
  else
    suf_list="${suf_list},$suf"
  fi
done

loginfo() {
  echo "$*"
}

process_files() {
  local file_id=0
  for ff in "${@}" ; do
    if [ -d "$ff" ] ; then
      continue
    fi
    ((file_id += 1))
    if [ "$file_id" -gt 1 ] ; then
      echo $'\n\n================================'
    fi
    loginfo "Log file #$file_id: $ff"
    cat "$ff"
  done
}

if [ "${#suffix[@]}" -gt 1 ] ; then
  suf_comma_list="$(echo "${suf_list[*]}" | tr ' ' ',')"
  eval "process_files ./**/*.{$suf_comma_list}"
else
  eval "process_files ./**/*.$suf_list"
fi
