#!/usr/bin/env bash

set -eu

# 执行前git fetch -p
# todo: is_remote_tracked

declare -a local_branches
declare -a local_tags

local_branches=($(git branch '--format=%(refname)' | sed 's;^refs/heads/;;'))
local_tags=($(git tag -l))

is_remote_tracked() {
  local ref_name=
  ref=$1
  {
    while read -r ref_name ; do
      if [[ "$ref_name" =~ ^refs/remotes/ ]] ; then
        return 0
      fi
    done
  } < <(git for-each-ref '--format=%(refname)' "--points-at=$ref")

  return 1
}

process_refs() {
  local is_tag=$1
  shift
  local ref_type=
  if $is_tag ; then
    ref_type=tag
  else
    ref_type=branch
  fi

  for ref in "$@" ; do
    child_info="$(git_child "$ref")"
    if ! [[ "${child_info}" =~ [^[:space:]] ]] && ! is_remote_tracked "$ref" ; then
      echo "Cannot safe delete ref($ref) because it's a leaf"
      continue
    fi

    echo "Should proceed to delete $ref_type: ${ref}, y/n?"
    read -r confirmation || continue
    if [ "$(echo "${confirmation:-}" | tr '[:upper:]' '[:lower:]')" != y ] ; then
      continue
    fi

    if $is_tag ; then
      git tag -d "$ref"
    else
      git branch -D "$ref"
    fi
  done
}

process_refs 'false' "${local_branches[@]:+${local_branches[@]}}"
process_refs 'true' "${local_tags[@]:+${local_tags[@]}}"
