#!/bin/bash
{
  for ff in ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision ; do
    echo "file: $ff"
    security cms -D -i "$ff"
    echo
    echo
    echo
    echo
    echo
  done
} | vim -
