#!/usr/bin/env bash
set -eu
if ! shopt -s nullglob globstar ; then
  os_name="$(uname | tr '[:upper:]' '[:lower:]')"
  if [ "$os_name" = "darwin" ] ; then
    brew install bash
  elif [ "$os_name" = "linux" ] ; then
    sudo apt install bash
  else
    printf 'Very ancient version of bash detected. Go update it.\n'
  fi
  exit 1
fi

is_on=
if [ "${1:-}" = on ] ; then
  is_on=true
elif [ "${1:-}" = off ] ; then
  is_on=false
else
  echo "Usage: $0 <on|off>"
  exit 1
fi

if $is_on ; then
  set -x
  ssh tc2 '[[ "`docker container ls --filter name=ss --format '\
'"{{.Status}}"'\
'`" =~ Up.+ ]] || docker container restart ss'
else
  set -x
  ssh tc2 'docker container stop ss'
fi

