#!/usr/bin/env bash
set -e

history_file=.simdo.hist
if [ -n "$SHELLPACK_HOME" ] ; then
  history_file="${SHELLPACK_HOME}/$history_file"
fi

declare -a pass_args_shellpack_lru_entry=(\
  '--name' 'simlog-entry' \
  '--session-file' "$history_file" \
)

trim_entry() {
  sed 's/^[[:blank:]]\{1,\}//' | \
    sed 's/[[:blank:]]\{1,\}$//' | \
    sed '/^[[:blank:]]*#/ d' | \
    sed '/^$/ d'
}

entry=$(shellpack_lru_entry "${pass_args_shellpack_lru_entry[@]}")
rc=$?
if [ "$rc" -eq 2 ] ; then
  exit
elif [ "$rc" -ne 0 ] ; then
  exit 1
fi

declare -a real_entry
real_entry=($(echo "$entry" | trim_entry))

xcrun simctl "${real_entry[@]}"
