#!/usr/bin/env bash
set -e

device_id=$(simget)
if [ -z "$device_id" ] ; then
  exit 1
fi

pass_args=()
while [ "$#" -gt 0 ] ; do
  key="$1"
  case $key in
      *)
      pass_args+=("$1")
      shift
      ;;
  esac
done

xcrun simctl spawn "$device_id" log stream "${pass_args[@]}"
