#!/usr/bin/env bash
set -eu

which_remote=origin
commit=
is_no_remote=false
while [ "$#" -gt 0 ] ; do
  key="$1"
  case $key in
      --remote)
        which_remote="$2"
        shift ; shift
        ;;
      --no-remote)
        is_no_remote=true
        shift
        ;;
      *)
        if [ -z "$commit" ] ; then
          commit="$key"
        fi
      shift
      ;;
  esac
done

if [ -z "$commit" ] ; then
  commit='head'
fi

declare -a branches=()
IFS_="$IFS"
IFS=$'\n'
get_refs() {
  git for-each-ref --format="%(refname)" \
    --contains "$commit" \
    refs/heads refs/tags "refs/remotes/$which_remote"
}
branches+=($(get_refs))
IFS="$IFS_"

declare -a all_ref_ranges=()
for ref in "${branches[@]}" ; do
  all_ref_ranges+=("${commit}..${ref}")
done

git log --graph --oneline --decorate --color --abbrev-commit \
  --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cd) %C(bold blue)<%an>%Creset' \
  --date=format-local:'%Y-%m-%d %z %a' "$@" "${all_ref_ranges[@]}"
