#!/usr/bin/env bash
# TODO: wansong, what is this?
set -eu
if ! shopt -s nullglob globstar ; then
  os_name="$(uname | tr '[:upper:]' '[:lower:]')"
  if [ "$os_name" = "darwin" ] ; then
    brew install bash
  elif [ "$os_name" = "linux" ] ; then
    sudo apt install bash
  else
    printf 'Very ancient version of bash detected. Go update it.\n'
  fi
  exit 1
fi

objects=()
{
  while read -r match_word obj_type obj_id ; do
    if [ "$match_word" != "unreachable" ] ; then
      continue
    fi
    echo "type: ${obj_type}, id: ${obj_id}"
    objects+=("$obj_id")
  done
} < <(git fsck --unreachable)

git show "${objects[@]}"
